"""new

Revision ID: 05352bd17cfb
Revises: 8b31d47aae90
Create Date: 2022-02-23 00:42:57.052469

"""
from alembic import op
import sqlalchemy as sa
from app import enums


# revision identifiers, used by Alembic.
revision = '05352bd17cfb'
down_revision = '8b31d47aae90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('shift_time', enums.ValueEnum('shift_time', sa.Enum('00:00-08:00', '08:00-16:00', '16:00-00:00', name='shifttime'), nullable=True)))
    op.add_column('log', sa.Column('team', enums.ValueEnum('team', sa.Enum('А', 'Б', 'В', 'Г', 'Д', name='team'), nullable=True)))
    op.add_column('log', sa.Column('oper_notes', sa.Text(), nullable=True))
    op.add_column('log', sa.Column('defects', sa.Text(), nullable=True))
    op.drop_index('ix_log_pub_date', table_name='log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_log_pub_date', 'log', ['pub_date'], unique=False)
    op.drop_column('log', 'defects')
    op.drop_column('log', 'oper_notes')
    op.drop_column('log', 'team')
    op.drop_column('log', 'shift_time')
    # ### end Alembic commands ###
