"""is_active

Revision ID: 1d0ac50408bf
Revises: 475448e80c95
Create Date: 2022-02-20 15:00:33.729934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d0ac50408bf'
down_revision = '475448e80c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('is_active', sa.Boolean(), nullable=True))
    # op.drop_index('ix_log_pub_date', table_name='log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('ix_log_pub_date', 'log', ['pub_date'], unique=False)
    op.drop_column('log', 'is_active')
    # ### end Alembic commands ###
