"""log enums

Revision ID: 89b1b122e518
Revises: ffb1b960b410
Create Date: 2022-02-20 01:26:29.881572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b1b122e518'
down_revision = 'ffb1b960b410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log', sa.Column('pub_date', sa.Date(), nullable=True))
    op.alter_column('log', sa.Column('shift_time', sa.Enum('00:00-08:00', '08:00-16:00', '16:00-00:00', name='shifttime'), nullable=True))
    op.alter_column('log', sa.Column('team', sa.Enum('А', 'Б', 'В', 'Г', 'Д', name='team'), nullable=True))
    op.alter_column('log', sa.Column('oper_notes', sa.Text(), nullable=True))
    op.alter_column('log', sa.Column('defects', sa.Text(), nullable=True))
    # op.create_index(op.f('ix_log_pub_date'), 'log', ['pub_date'], unique=False)
    with op.batch_alter_table('log') as batch_op:
        batch_op.drop_column('text')
    # op.drop_column('log', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('pub_date', sa.DATETIME(), nullable=True))
    op.add_column('log', sa.Column('text', sa.TEXT(), nullable=True))
    op.drop_index(op.f('ix_log_date'), table_name='log')
    op.create_index('ix_log_pub_date', 'log', ['pub_date'], unique=False)
    op.drop_column('log', 'defects')
    op.drop_column('log', 'oper_notes')
    op.drop_column('log', 'team')
    op.drop_column('log', 'shift_time')
    op.drop_column('log', 'date')
    # ### end Alembic commands ###
