"""empty message

Revision ID: 8b31d47aae90
Revises: 1d0ac50408bf
Create Date: 2022-02-21 15:12:49.250922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b31d47aae90'
down_revision = '1d0ac50408bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('is_accepted', sa.Boolean(), nullable=True))
    # op.drop_index('ix_log_pub_date', table_name='log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('ix_log_pub_date', 'log', ['pub_date'], unique=False)
    op.drop_column('log', 'is_accepted')
    # ### end Alembic commands ###
