"""Choise equip

Revision ID: cc0b9a8c6bec
Revises: 91dee9007e0e
Create Date: 2022-02-20 14:31:02.438336

"""
from alembic import op
import sqlalchemy as sa
from app.enums import ChoiceType
from app.choises import equipment

# revision identifiers, used by Alembic.
revision = 'cc0b9a8c6bec'
down_revision = '91dee9007e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('equipment_run', ChoiceType(equipment), nullable=True))
    # op.drop_index('ix_log_pub_date', table_name='log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('ix_log_pub_date', 'log', ['pub_date'], unique=False)
    op.drop_column('log', 'equipment_run')
    # ### end Alembic commands ###
